import { useAuth } from '@/src/auth/AuthProvider';
import { Card, PixelLabel, PrimaryButton, Progress, Screen } from '@/src/components/BbUi';
import { bb } from '@/src/theme/tokens';
import { StyleSheet, Text, View } from 'react-native';
export default function ProfileScreen(){
 const{user,signOut}=useAuth();if(!user)return null;const xp=user.xp%500;
 return <Screen><PixelLabel tone={bb.colors.emerald}>PLAYER CARD</PixelLabel><Text style={s.title}>Profile</Text><Card accent={bb.colors.emerald}><View style={s.row}><View style={s.avatar}><Text style={s.avatarText}>{user.fullName.slice(0,1).toUpperCase()}</Text></View><View style={s.flex}><Text style={s.name}>{user.fullName}</Text><Text style={s.muted}>Level {user.level} · Expense Ranger</Text></View><Text style={s.xp}>{Math.round(user.xp)} XP</Text></View><Progress value={xp/500}/><Text style={s.muted}>{Math.round(xp)} / 500 XP to next level</Text></Card>
 <View style={s.grid}><Card style={s.stat}><PixelLabel tone={bb.colors.gold}>STREAK</PixelLabel><Text style={s.number}>{user.currentStreak}</Text><Text style={s.muted}>days</Text></Card><Card style={s.stat}><PixelLabel tone={bb.colors.violet}>ROLE</PixelLabel><Text style={s.number}>●</Text><Text style={s.muted}>Player</Text></Card></View>
 <Card><PixelLabel tone={bb.colors.cyan}>ACCOUNT & PRIVACY</PixelLabel><Text style={s.muted}>{user.email}</Text><Text style={s.muted}>Security · Notifications · AI data permissions · Accessibility</Text></Card><PrimaryButton onPress={signOut}>SIGN OUT</PrimaryButton></Screen>
}
const s=StyleSheet.create({title:{color:bb.colors.text,fontSize:28,fontWeight:'800'},row:{flexDirection:'row',alignItems:'center',gap:12},avatar:{width:56,height:56,borderRadius:16,backgroundColor:bb.colors.raised,borderWidth:1,borderColor:bb.colors.emerald,alignItems:'center',justifyContent:'center'},avatarText:{color:bb.colors.emerald,fontSize:24,fontWeight:'900'},flex:{flex:1},name:{color:bb.colors.text,fontSize:20,fontWeight:'800'},muted:{color:bb.colors.muted,fontSize:13,lineHeight:20},xp:{color:bb.colors.gold,fontFamily:'monospace',fontSize:11,fontWeight:'800'},grid:{flexDirection:'row',gap:12},stat:{flex:1},number:{color:bb.colors.text,fontSize:30,fontWeight:'900'}})
